### PR TITLE
Modified slice layer to handle cases where size contains -1's

### PR DESCRIPTION
**Pull request by DawerG**
1) Cases requiring simultaneous slice across height, width and channel not handled yet.

2) For 4 dimensional blob, handled slice across the channel axis.

### CODE REVIEW

**Comment by aseemw** [comment]
Good to merge after a test has been added. 

Should resolve PR#270

**Comment by lauriebyrum** [comment]
Hi, what's up with this change? Can it get merged please? Thanks!

**Comment by lauriebyrum** [comment]
FYI: this will NOT fix 270. 270 is about strided_slice. This is about slice.

**Comment by bhushan23** [comment]
@gdawer @aseemw do we want to merge this in?

**Pull request merged**
